### PR TITLE
PR to test deployment

### PR DESCRIPTION
**Pull request by martinjaeger**
- Overcurrent + thermal model ready for review
- Short circuit: incomplete draft
- Overvoltage ready for review

### CODE REVIEW

**Comment by martinjaeger** [comment]
Result of test: Travis CI deployment does not work for pull requests.

**Comment by jurra** [comment]
Martin what are you using to deploy??

**Comment by martinjaeger** [comment]
I'm using Travis CI, which allows automatic deployment to gh-pages. For configuration see [.travis.yml](https://github.com/LibreSolar/learn.libre.solar/blob/master/.travis.yml).

Before that, the vuepress data is prepared using my own [deploy.sh script](https://github.com/LibreSolar/learn.libre.solar/blob/master/deploy.sh).

Unfortunately, Travis CI does not start the deployment for safety reasons if it is triggered by a pull-request. Essentially, everyone can send a PR, and if there is something harmful, that would get published without anyone checking it before. So this might make sense in general, but for a static website it should not be a big issue, as you can't easily inject harmful code...

If you use a PR as an internal collaborator, the created branch is accessible via learn.libre.solar/b/your-branch, so that's fine.

**Comment by jurra** [comment]
Alright, I was going to point to a bash script for deployment, i see you
are already doing that ;)

**Pull request closed without merging**
